export const DEFAULT_REDIS_NAMESPACE = Symbol('DEFAULT_REDIS_NAMESPACE');

export const REDIS_CLIENTS = Symbol('REDIS_CLIENTS');

export const REDIS_CLIENTS_PROVIDERS = Symbol('REDIS_CLIENTS_PROVIDERS');

export const REDIS_MODULE_OPTIONS = Symbol('REDIS_MODULE_OPTIONS');

export const REDIS_MERGED_MODULE_OPTIONS = Symbol(
  'REDIS_MERGED_MODULE_OPTIONS',
);

export const REDIS_MODULE_NAME = 'REDIS_MODULE';
